name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
permissions:
  pull-requests: write
  checks: write
jobs:  
  build:
    env:
      PUBLISH_NUGET: true # if true a nuget will be published on version change
      MAIN_CSPROJ: 'src/interactiveCLI/interactiveCLI.csproj' # main project (for nuget packaging)
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Clean artifacts and nugets 
      run: dotnet clean  --configuration Release && dotnet nuget locals all --clear
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: publish nuget
      if:  ${{success() && matrix.os == 'ubuntu-latest' && env.PUBLISH_NUGET}}
      id: publish_nuget
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          VERSION_REGEX: <version>(.*)<\/version>  
          PROJECT_FILE_PATH: ${{env.MAIN_CSPROJ}}
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          VERSION_FILE_PATH: ${{env.MAIN_CSPROJ}}
          INCLUDE_SYMBOLS: true

